config/routes.rb
Jqueryfileuploadrailscarrierwave::Application.routes.draw do

  get "result/expression"

  get "result/mapping"

  get "result/quality"

  get "result/showquality"

  get "result/showqualityDetails"

  get "result/transcript"

  get "result/trim"

  resources :step_qas


  resources :pipelines


  resources :analyses


  get "static_pages/help"

  devise_for :users

  resources :documents

  root to: 'home#index' 

  devise_scope :user do
     get "sign_in", :to => "devise/sessions#new"
     get "sign_out", :to => "devise/sessions#destroy"
     get "sign_up", :to => "devise/registrations#new"
     get "edit", :to => "devise/registrations#edit"
 end
 
end

app/models/pipeline.rb
class Pipeline < ActiveRecord::Base
    attr_accessible :name, :comments, :analysis_id
end

app/controllers/pipelines_controller.rb
class PipelinesController < ApplicationController
  before_filter :set_pipeline, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    if !params[:analysis_id].nil?
      @analysis_id = params[:analysis_id]
      session[:analysis_id] = params[:analysis_id]
    else
      if not session[:analysis_id].nil?
        @analysis_id = session[:analysis_id]
      end
    end
    @analysis = Analysis.find(@analysis_id)  
    @pipelines = Pipeline.where("analysis_id = " + @analysis.id.to_s)
    respond_with(@pipelines)
  end

  def show
    redirect_to(:action => :index)
  end

  def new
    @pipeline = Pipeline.new
    #respond_with(@pipeline)
  end

  def edit
  end

  def create
    @pipeline = Pipeline.new(params[:pipeline])
    @pipeline.analysis_id =  session[:analysis_id]
    @pipeline.save  
    session[:pipeline_id] = @pipeline.id  
    respond_with(@pipeline)
  end

  def update
    @pipeline.update_attributes(params[:pipeline])
    respond_with(@pipeline)
  end

  def destroy
    @pipeline.destroy
    respond_with(@pipeline)
  end

  private
    def set_pipeline
      @pipeline = Pipeline.find(params[:id])
    end
end

app/helpers/pipelines_helper.rb
module PipelinesHelper
end

app/views/pipelines/_form.html.erb
<%= form_for(@pipeline) do |f| %>

  <% if @pipeline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pipeline.errors.count, "error") %> prohibited this pipeline from being saved:</h2>
      <ul>
      <% @pipeline.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-xs-12 form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, :placeholder => "Project Name", :tabindex => 1, :required => true, class:"form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 form-group">
      <%= f.label :comments %><br>
      <%= f.text_area :comments, :rows => "5", :placeholder => "Comments", :tabindex => 1, :required => true, class:"form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 form-group">
      <%= f.button "Confirm", class: "btn btn-large btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Saving..."} %>
      <%= link_to "Cancel", :back, {:class=>"btn btn-danger"} %>
    </div>
  </div>
<% end %>

app/views/pipelines/edit.html.erb
<br>
<div class="row">
	<div id="projects_form">
		<div class="col-xs-12 col-sm-6 col-sm-offset-3">
			<div class="panel panel-default">
		    	<div class="panel-heading">
		          	<h4 class="panel-title">
		          		<i class="fa fa-pencil-square-o fa-2x"></i>
		              &nbsp Edit Project
		          	</h4>
		    	</div>
		    	<div class="panel-body">
					<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pipelines/index.html.erb
<!-- ======== @Region: #content ======== -->
<div id="contentProject">
    <ol class="breadcrumb">
      <li><a href="/">Home</a></li>
      <li><%= link_to "Analysis" ,analyses_path, :method => :get%></li>
      <li class="active">Project</li>
    </ol>
  <div class="container">
    <div class = "row">
        <div class="col-sm-12 col-md-4">
          <div class="panel panel-default">
              <!-- Default panel contents -->
            <div class="panel-heading">
              Analysis Title:&nbsp<%= @analysis.title %>
            </div>
            <div class="panel-body">
              <%= @analysis.details%>
            </div>
          </div>
        </div>
        <div class="col-sm-12 col-md-12">
          <%= button_to '  New  ', new_pipeline_path,  :method => :get, :class => 'btn btn-primary'%>
          <p></p>
          <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
              <h4 class="panel-title"><i class="fa fa-cog fa-2x"></i>&nbsp Projects</h4>
            </div>
            <div class="panel-body">
              <p></p> <!-- Line Space -->
              <!-- Table --> 
              <div class="table-responsive">  
                <table id="table"  class="table">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Comments</th>
                      <th>Last Update</th>
                      <th>Create At</th>
                      <th></th>
                    </tr>
                  </thead>
                  <% @pipelines.each do |pipeline| %>
                  <tr>
                    <td><%= pipeline.name %></td>
                    <td ><%= pipeline.comments %></td>
                    <td width="100px"><%= time_ago_in_words(pipeline.updated_at) %></td>
                    <td width="130px"><%= pipeline.created_at.strftime("%F %T") %></td>
                    <td width="280px">          
                      <%= link_to  "".html_safe, new_step_qa_path(:analysis_id => session[:analysis_id],:pipeline_id => pipeline,), :class => 'btn btn-info fa fa-cogs'%>  
                      <%= link_to "".html_safe, edit_pipeline_path(pipeline), :class => 'btn btn-primary fa fa-pencil'%>
                      <%= link_to "".html_safe, documents_path(:pipeline_id => pipeline), :class => 'btn btn-warning cancel fa fa-file'%>                    
                      <%= link_to "".html_safe ,pipeline_path(pipeline),
                      :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger fa fa-trash-o' %>
                    </td>
                  </tr>
                  <% end %>
                </table>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>
<%= javascript_include_tag 'dataTable/jquery-dataTables.js' %>
<script type="text/javascript">
    $(document).ready(function(){
      $("#table").dataTable({
      "aaSorting": [[0, "asc"]]
      });
    });
</script>
<style type="text/css">
    table { 
      table-layout: fixed;
      width: 100%
    }
</style>

app/views/pipelines/new.html.erb
<br>
<div class="row">
	<div id="projects_form">
		<div class="col-xs-12 col-sm-6 col-sm-offset-3">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h4 class="panel-title">
						<i class="fa fa-plus-square-o fa-2x"></i>
						&nbsp New Project
					</h4>
				</div>
				<div class="panel-body">
					<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
	</div>
</div>

app/views/pipelines/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_pipeline_path(@pipeline) %> |
<%= link_to 'Back', pipelines_path %>