config/routes.rb
Jqueryfileuploadrailscarrierwave::Application.routes.draw do

  get "result/expression"

  get "result/mapping"

  get "result/quality"

  get "result/showquality"

  get "result/showqualityDetails"

  get "result/transcript"

  get "result/trim"

  resources :step_qas


  resources :pipelines


  resources :analyses


  get "static_pages/help"

  devise_for :users

  resources :documents

  root to: 'home#index' 

  devise_scope :user do
     get "sign_in", :to => "devise/sessions#new"
     get "sign_out", :to => "devise/sessions#destroy"
     get "sign_up", :to => "devise/registrations#new"
     get "edit", :to => "devise/registrations#edit"
 end
 
end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :file, :filetype

  mount_uploader :file, FileUploader
  
  def to_jq_upload
    {
      "name" => read_attribute(:file),
      "size" => file.size,
      "url" => file.url,
      "delete_url" => "/documents/#{id}",
      "delete_type" => "DELETE"
    }
  end

  def self.load_filetypes
    types = {
      'Please Choose...' => '',
      'Genome Data (Bed Files)' => '1',
      'Mapped Reads' => '2',
      'Reference Genomes' => '3',
      'Control / Test Files (.fasta .fastaq)' => '4',
    }
    #types.sort { |a, b| a[1] <=> b[1] }
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  # GET /documents
  # GET /documents.json
  def index
    if !params[:pipeline_id].nil?
      @pipeline_id = params[:pipeline_id]
      session[:pipeline_id] = params[:pipeline_id]
    else
      if not session[:pipeline_id].nil?
        @pipeline_id = session[:pipeline_id]
      end
    end
    if !params[:analysis_id].nil?
      @analysis_id = params[:analysis_id]
      session[:analysis_id] = params[:analysis_id]
    else
      if not session[:analysis_id].nil?
        @analysis_id = session[:analysis_id]
      end
    end    
    
    @pipelines = Pipeline.find(@pipeline_id)
    @documents = Document.where("pipeline_id = " + @pipeline_id.to_s)

    respond_to do |format|
      format.html # index.html.erb
      # format.json { render json: @documents }
      format.json { render json: @documents.map{|document| document.to_jq_upload } }
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    redirect_to(:action => :index)
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])

    # Load Combobox data
    @filetypes = Document.load_filetypes
      
logger.debug "==================================================="
logger.debug  @filetypes
logger.debug "==================================================="

  end

  # POST /documents
  # POST /documents.json
  def create

    @document = Document.new(params[:document])
    respond_to do |format|
      @document.pipeline_id =  session[:pipeline_id]
      if @document.save

          @dir = "#{Rails.root}/Analysis/#{@document.id}/"
          @subdir = @dir+"/files/controle"
          @contrdir = @dir+"/files"
          @plotpath = @subdir+"/plot"
          @alignpath = @subdir+"/alignments"
          @trimmedpath = @subdir+"/trimmed"

          FileUtils.mkdir_p(@dir) unless File.directory?(@dir)
          FileUtils.mkdir_p(@subdir) unless File.directory?(@subdir)
          FileUtils.mkdir_p(@plotpath) unless File.directory?(@plotpath)        
          FileUtils.mkdir_p(@alignpath) unless File.directory?(@alignpath)
          FileUtils.mkdir_p(@trimmedpath) unless File.directory?(@trimmedpath)

          FileUtils.chmod 0777, @dir, :verbose => true
          FileUtils.chmod 0777, @subdir 
          FileUtils.chmod 0777, @contrdir
          FileUtils.chmod 0777, @plotpath
          FileUtils.chmod 0777, @alignpath
          FileUtils.chmod 0777, @trimmedpath

          format.html {
            render :json => [@document.to_jq_upload].to_json,
            :content_type => 'text/html',
            :layout => false
          }
          format.json { render json: {files: [@document.to_jq_upload]}, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end    
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
	def showFileType id
		case id
		when 1
			'Genome Data (Bed Files)'
		when 2
			'Mapped Reads'
		when 3
			'Reference Genomes'
		when 4
			'Control / Test Files (.fasta .fastaq)'
		else
			'Please Choose...'
		end
	end
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-xs-12 form-group">
      <%= f.label :File_Name %><br>
    <%= f.text_field :file,:readonly => true, class:"form-control" %>
    </div>
  </div>
   <div class="row">
    <div class="col-xs-12 form-group">
      <%= f.label :File_type %><br>
      <%= f.select :filetype, @filetypes,:selected => @document.filetype, class:"form-group" %>
    </div>
  </div>
   
  <div class="row">
    <div class="col-xs-12 form-group">
      <%= f.button "Confirm", class: "btn btn-large btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Saving..."} %>
      <%= link_to "Cancel", :back, {:class=>"btn btn-danger"} %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('.combobox').combobox();
  });
</script>

app/views/documents/edit.html.erb
<br>
<div class="row">

		<div class="col-xs-12 col-sm-6 col-sm-offset-3">
			<div class="panel panel-default">
		    	<div class="panel-heading">
		          	<h4 class="panel-title">
		          		<i class="fa fa-pencil-square-o fa-2x"></i>
		              &nbsp Edit File
		          	</h4>
		    	</div>
		    	<div class="panel-body">
					<%= render 'form' %>
				</div>
			</div>
		</div>

</div>

app/views/documents/index.html.erb
<!-- ======== @Region: #content ======== -->
<div id="contentPipe">
    <ol class="breadcrumb">
      <li><a href="/">Home</a></li>
      <li><%= link_to "Analysis" ,analyses_path, :method => :get%></li>
      <li><%= link_to "Project" ,pipelines_path, :method => :get%></li>
      <li class="active">Files</li>
    </ol>
  <div class="container">
    <div class = "row">
      <div class="col-sm-12 col-md-12">
        <%= button_to '  Upload File(s)  ', new_document_path,  :method => :get, :class => 'btn btn-primary'%>
        <p></p>
        <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading">
            <h4 class="panel-title"><i class="fa fa-file fa-2x"></i>&nbsp Files</h4>
          </div>
          <div class="panel-body">
            <p></p> <!-- Line Space -->
            <!-- Table --> 
            <div class="table-responsive">  
              <table id="table"  class="table">
                <thead>
                  <tr>
                    <th class="FileName">FileName</th>
                    <th class="Size">Size</th>
                    <th class="Type">Type</th>
                    <th class="LastUpdate">Last Update</th>
                    <th class="CreatAt">Create At</th>
                    <th class="Options"></th>
                  </tr>
                </thead>
                <% @documents.each do |document| %>
                <tr>
                  <td style="word-wrap: break-word"><%= filename = File.basename(document.file.to_s)  %></td>
                  <td><%= document.size %></td>
                  <td><%= showFileType(document.filetype) %></td>
                  <td><%= time_ago_in_words(document.updated_at) %></td>
                  <td><%= document.created_at.strftime("%F %T") %></td>
                  <td>           
                    <%= link_to "".html_safe, edit_document_path(document), :class => 'btn btn-primary fa fa-pencil'%>                  
                    <%= link_to "".html_safe ,document_path(document),
                        :method => :delete, 
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, 
                        :class => 'btn btn-danger fa fa-trash-o' %>
                  </td>
                </tr>
                <% end %>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag 'dataTable/jquery-dataTables.js' %>
<script type="text/javascript">
    $(document).ready(function(){
      $("#table").dataTable({
      "aaSorting": [[0, "asc"]]
      });
    });
</script>

<style type="text/css">
    table { 
      table-layout: fixed;
      width: 100%
    }
    th.FileName {
      width: 15%
    }
    th.Size {
      width: 10%; 
    }
    th.Type {
      width: 20%; 
    }    
    th.LastUpdate {
      width: 15%; 
    }    
    th.CreatAt {
      width: 15%; 
    }
    th.Options {
      width: 10%; 
    }
</style>

app/views/documents/new.html.erb
<!-- ======== @Region: #content ======== -->
<div id="contentPipe">
    <ol class="breadcrumb">
      <li><a href="/">Home</a></li>
      <li><%= link_to "Analysis" ,analyses_path, :method => :get%></li>
      <li><%= link_to "Project" ,pipelines_path, :method => :get%></li>
      <li><%= link_to "Files" ,documents_path, :method => :get%></li>
      <li class="active">Upload</li>
    </ol>
  <div class="container">
    <div class = "row">
      <%= form_for @document, :html => { :multipart => true, :id => "fileupload"  } do |f| %>
        <!-- Redirect browsers with JavaScript disabled to the origin page -->
        <noscript><input type="hidden" name="redirect" value="http://blueimp.github.io/jQuery-File-Upload/"></noscript>
        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
        <div class="row fileupload-buttonbar">
          <div class="span7">
            <!-- The fileinput-button span is used to style the file input field as button -->
            <span class="btn btn-success fileinput-button">
              <i class="icon-plus icon-white"></i>
              <span>Add files...</span>
              <%= f.file_field :file, multiple: true, id: 'upload-field' %>
            </span>
            <button type="submit" class="btn btn-primary start">
              <i class="icon-upload icon-white"></i>
              <span>Start upload</span>
            </button>
            <button type="reset" class="btn btn-warning cancel">
              <i class="icon-ban-circle icon-white"></i>
              <span>Cancel upload</span>
            </button>
            <button type="button" class="btn btn-danger delete">
              <i class="icon-trash icon-white"></i>
              <span>Delete</span>
            </button>
            <input type="checkbox" class="toggle">
            <!-- The loading indicator is shown during file processing -->
            <span class="fileupload-loading"></span>
            <p>Drag and Drop files here o click the Add files button.</p>
          </div>    
        </div>
        <!-- The global progress information -->
        <div class="span5 fileupload-progress fade">
          <!-- The global progress bar -->
          <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
            <div class="bar" style="width:0%;"></div>
          </div>
          <!-- The extended global progress information -->
          <div class="progress-extended">&nbsp;</div>
        </div>
        <!-- The table listing the files available for upload/download -->
        <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
      <% end %>
    </div>
  </div>
</div>


<script>
  var fileUploadErrors = {
  maxFileSize: 'File is too big',
  minFileSize: 'File is too small',
  acceptFileTypes: 'Filetype not allowed',
  maxNumberOfFiles: 'Max number of files exceeded',
  uploadedBytes: 'Uploaded bytes exceed file size',
  emptyResult: 'Empty file upload result'
  };
</script>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  <tr class="template-upload fade">
    <td class="preview"><span class="fade"></span></td>
    <td class="name"><span>{%=file.name%}</span></td>
    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
    {% if (file.error) { %}
    <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
    {% } else if (o.files.valid && !i) { %}
    <td>
      <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
    </td>
    <td class="start">{% if (!o.options.autoUpload) { %}
      <button class="btn btn-primary">
        <i class="icon-upload icon-white"></i>
        <span>{%=locale.fileupload.start%}</span>
      </button>
      {% } %}</td>
    {% } else { %}
    <td colspan="2"></td>
    {% } %}
    <td class="cancel">{% if (!i) { %}
      <button class="btn btn-warning">
        <i class="icon-ban-circle icon-white"></i>
        <span>{%=locale.fileupload.cancel%}</span>
      </button>
      {% } %}</td>
  </tr>
  {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
      {% if (file.error) { %}
        <td></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
        <td class="preview">{% if (file.thumbnail_url) { %}
          <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
          {% } %}</td>
        <td class="name">
          <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
        </td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td colspan="2"></td>
        {% } %}
      <td class="delete">
        <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
          <i class="icon-trash icon-white"></i>
          <span>{%=locale.fileupload.destroy%}</span>
        </button>
        <input type="checkbox" name="delete" value="1">
      </td>
    </tr>
    {% } %}
</script>

<script type="text/javascript" charset="utf-8">
  $(function () {
      // Initialize the jQuery File Upload widget:
      $('#fileupload').fileupload({
        paramName: 'document[file]'
      });
      // 
      // Load existing files:
      $.getJSON($('#fileupload').prop('action'), function (files) {
        var fu = $('#fileupload').data('blueimpFileupload'), 
          template;
        fu._adjustMaxNumberOfFiles(-files.length);
        console.log(files);
        template = fu._renderDownload(files)
          .appendTo($('#fileupload .files'));
        // Force reflow:
        fu._reflow = fu._transition && template.length &&
          template[0].offsetWidth;
        template.addClass('in');
        $('#loading').remove();
      });

  });
</script>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>File:</b>
  <%= @document.file %>
</p>


<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>